language: elixir

elixir:
  - 1.6

otp_release:
  - 21.0

install:
  - mix local.rebar --force; mix local.hex --force; mix deps.get

env:
  - MIX_ENV=test

script:
  - mix test
  - mix coveralls.travis
